import { Language } from "../models/language.model";

export var languages: Language[] = [
  { code: "af", name: "Afrikaans", name2: "Afrikaans" },
  { code: "sq", name: "Albanian", name2: "Albanian - shqip" },
  { code: "am", name: "Amharic", name2: "Amharic - አማርኛ" },
  { code: "ar", name: "Arabic", name2: "Arabic - العربية" },
  { code: "an", name: "Aragonese", name2: "Aragonese - aragonés" },
  { code: "hy", name: "Armenian", name2: "Armenian - հայերեն" },
  { code: "ast", name: "Asturian", name2: "Asturian - asturianu" },
  { code: "az", name: "Azerbaijani", name2: "Azerbaijani - azərbaycan dili" },
  { code: "eu", name: "Basque", name2: "Basque - euskara" },
  { code: "be", name: "Belarusian", name2: "Belarusian - беларуская" },
  { code: "bn", name: "Bengali", name2: "Bengali - বাংলা" },
  { code: "bs", name: "Bosnian", name2: "Bosnian - bosanski" },
  { code: "br", name: "Breton", name2: "Breton - brezhoneg" },
  { code: "bg", name: "Bulgarian", name2: "Bulgarian - български" },
  { code: "ca", name: "Catalan", name2: "Catalan - català" },
  { code: "ckb", name: "Central Kurdish", name2: "Central Kurdish - کوردی (دەستنوسی عەرەبی)<" },
  { code: "zh", name: "Chinese", name2: "Chinese - 中文" },
  { code: "zh-HK", name: "Chinese (Hong Kong)", name2: "Chinese (Hong Kong) - 中文（香港）" },
  { code: "zh-CN", name: "Chinese (Simplified)", name2: "Chinese (Simplified) - 中文（简体）" },
  { code: "zh-TW", name: "Chinese (Traditional)", name2: "Chinese (Traditional) - 中文（繁體）" },
  { code: "co", name: "Corsican", name2: "Corsican" },
  { code: "hr", name: "Croatian", name2: "Croatian - hrvatski" },
  { code: "cs", name: "Czech", name2: "Czech - čeština" },
  { code: "da", name: "Danish", name2: "Danish - dansk" },
  { code: "nl", name: "Dutch", name2: "Dutch - Nederlands" },
  { code: "en", name: "English", name2: "English" },
  { code: "en-AU", name: "English (Australia)", name2: "English (Australia)" },
  { code: "en-CA", name: "English (Canada)", name2: "English (Canada)" },
  { code: "en-IN", name: "English (India)", name2: "English (India)" },
  { code: "en-NZ", name: "English (New Zealand)", name2: "English (New Zealand)" },
  { code: "en-ZA", name: "English (South Africa)", name2: "English (South Africa)" },
  { code: "en-GB", name: "English (United Kingdom)", name2: "English (United Kingdom)" },
  { code: "en-US", name: "English (United States)", name2: "English (United States)" },
  { code: "eo", name: "Esperanto", name2: "Esperanto - esperanto" },
  { code: "et", name: "Estonian", name2: "Estonian - eesti" },
  { code: "fo", name: "Faroese", name2: "Faroese - føroyskt" },
  { code: "fil", name: "Filipino", name2: "Filipino" },
  { code: "fi", name: "Finnish", name2: "Finnish - suomi" },
  { code: "fr", name: "French - français", name2: "French - français" },
  { code: "fr-CA", name: "Afrikaans", name2: "Afrikaans" },
  { code: "af", name: "French (Canada) - français (Canada)", name2: "French (Canada) - français (Canada)" },
  { code: "fr-FR", name: "French (France) - français (France)", name2: "French (France) - français (France)" },
  { code: "fr-CH", name: "French (Switzerland) - français (Suisse)", name2: "French (Switzerland) - français (Suisse)" },
  { code: "gl", name: "Galician - galego", name2: "Galician - galego" },
  { code: "ka", name: "Georgian - ქართული", name2: "Georgian - ქართული" },
  { code: "de", name: "German - Deutsch", name2: "German - Deutsch" },
  { code: "de-AT", name: "German (Austria) - Deutsch (Österreich)", name2: "German (Austria) - Deutsch (Österreich)" },
  { code: "de-DE", name: "German (Germany) - Deutsch (Deutschland)", name2: "German (Germany) - Deutsch (Deutschland)" },
  { code: "de-LI", name: "German (Liechtenstein) - Deutsch (Liechtenstein)", name2: "German (Liechtenstein) - Deutsch (Liechtenstein)" },
  { code: "de-CH", name: "German (Switzerland) - Deutsch (Schweiz)", name2: "German (Switzerland) - Deutsch (Schweiz)" },
  { code: "el", name: "Greek - Ελληνικά", name2: "Greek - Ελληνικά" },
  { code: "gn", name: "Guarani", name2: "Guarani" },
  { code: "gu", name: "Gujarati - ગુજરાતી", name2: "Gujarati - ગુજરાતી" },
  { code: "ha", name: "Hausa", name2: "Hausa" },
  { code: "haw", name: "Hawaiian - ʻŌlelo Hawaiʻi", name2: "Hawaiian - ʻŌlelo Hawaiʻi" },
  { code: "he", name: "Hebrew - עברית", name2: "Hebrew - עברית" },
  { code: "hi", name: "Hindi - हिन्दी", name2: "Hindi - हिन्दी" },
  { code: "hu", name: "Hungarian - magyar", name2: "Hungarian - magyar" },
  { code: "is", name: "Icelandic - íslenska", name2: "Icelandic - íslenska" },
  { code: "id", name: "Indonesian - Indonesia", name2: "Indonesian - Indonesia" },
  { code: "ia", name: "Interlingua", name2: "Interlingua" },
  { code: "ga", name: "Irish - Gaeilge", name2: "Irish - Gaeilge" },
  { code: "it", name: "Italian - italiano", name2: "Italian - italiano" },
  { code: "it-IT", name: "Italian (Italy) - italiano (Italia)", name2: "Italian (Italy) - italiano (Italia)" },
  { code: "it-CH", name: "Italian (Switzerland) - italiano (Svizzera)", name2: "Italian (Switzerland) - italiano (Svizzera)" },
  { code: "ja", name: "Japanese - 日本語", name2: "Japanese - 日本語" },
  { code: "kn", name: "Kannada - ಕನ್ನಡ", name2: "Kannada - ಕನ್ನಡ" },
  { code: "kk", name: "Kazakh - қазақ тілі", name2: "Kazakh - қазақ тілі" },
  { code: "km", name: "Afrikaans", name2: "Khmer - ខ្មែរ" },
  { code: "ko", name: "Afrikaans", name2: "Korean - 한국어" },
  { code: "ku", name: "Afrikaans", name2: "Kurdish - Kurdî" },
  { code: "ky", name: "Afrikaans", name2: "Kyrgyz - кыргызча" },
  { code: "lo", name: "Afrikaans", name2: "Lao - ລາວ" },
  { code: "la", name: "Afrikaans", name2: "Latin" },
  { code: "lv", name: "Afrikaans", name2: "Latvian - latviešu" },
  { code: "ln", name: "Afrikaans", name2: "Lingala - lingála" },
  { code: "lt", name: "Afrikaans", name2: "Lithuanian - lietuvių" },
  { code: "mk", name: "Afrikaans", name2: "Macedonian - македонски" },
  { code: "ms", name: "Afrikaans", name2: "Malay - Bahasa Melayu" },
  { code: "ml", name: "Afrikaans", name2: "Malayalam - മലയാളം" },
  { code: "mt", name: "Afrikaans", name2: "Maltese - Malti" },
  { code: "mr", name: "Afrikaans", name2: "Marathi - मराठी" },
  { code: "mn", name: "Afrikaans", name2: "Mongolian - монгол" },
  { code: "ne", name: "Afrikaans", name2: "Nepali - नेपाली" },
  { code: "no", name: "Afrikaans", name2: "Norwegian - norsk" },
  { code: "nb", name: "Afrikaans", name2: "Norwegian Bokmål - norsk bokmål" },
  { code: "nn", name: "Afrikaans", name2: "Norwegian Nynorsk - nynorsk" },
  { code: "oc", name: "Afrikaans", name2: "Occitan" },
  { code: "or", name: "Afrikaans", name2: "Oriya - ଓଡ଼ିଆ" },
  { code: "om", name: "Afrikaans", name2: "Oromo - Oromoo" },
  { code: "ps", name: "Afrikaans", name2: "Pashto - پښتو" },
  { code: "fa", name: "Afrikaans", name2: "Persian - فارسی" },
  { code: "pl", name: "Afrikaans", name2: "Polish - polski" },
  { code: "pt", name: "Afrikaans", name2: "Portuguese - português" },
  { code: "pt-BR", name: "Afrikaans", name2: "Portuguese (Brazil) - português (Brasil)" },
  { code: "pt-PT", name: "Afrikaans", name2: "Portuguese (Portugal) - português (Portugal)" },
  { code: "qu", name: "Afrikaans", name2: "Punjabi - ਪੰਜਾਬੀ" },
  { code: "ro", name: "Afrikaans", name2: "Romanian - română" },
  { code: "mo", name: "Afrikaans", name2: "Romanian (Moldova) - română (Moldova)" },
  { code: "rm", name: "Afrikaans", name2: "Romansh - rumantsch" },
  { code: "ru", name: "Afrikaans", name2: "Russian - русский" },
  { code: "gd", name: "Afrikaans", name2: "Scottish Gaelic" },
  { code: "sr", name: "Afrikaans", name2: "Serbian - српски" },
  { code: "sh", name: "Afrikaans", name2: "Serbo-Croatian - Srpskohrvatski" },
  { code: "sn", name: "Afrikaans", name2: "Shona - chiShona" },
  { code: "sd", name: "Afrikaans", name2: "Sindhi" },
  { code: "si", name: "Afrikaans", name2: "Sinhala - සිංහල" },
  { code: "sk", name: "Afrikaans", name2: "Slovak - slovenčina" },
  { code: "sl", name: "Afrikaans", name2: "Slovenian - slovenščina" },
  { code: "so", name: "Afrikaans", name2: "Somali - Soomaali" },
  { code: "st", name: "Afrikaans", name2: "Southern Sotho" },
  { code: "es", name: "Afrikaans", name2: "Spanish - español" },
  { code: "es-AR", name: "Afrikaans", name2: "Spanish (Argentina) - español (Argentina)" },
  { code: "es-419", name: "Afrikaans", name2: "Spanish (Latin America) - español (Latinoamérica)" },
  { code: "es-MX", name: "Afrikaans", name2: "Spanish (Mexico) - español (México)" },
  { code: "es-ES", name: "Afrikaans", name2: "Spanish (Spain) - español (España)<" },
  { code: "es-US", name: "Afrikaans", name2: "Spanish (United States) - español (Estados Unidos)" },
  { code: "su", name: "Afrikaans", name2: "Sundanese" },
  { code: "sw", name: "Afrikaans", name2: "Swahili - Kiswahili" },
  { code: "sv", name: "Afrikaans", name2: "Swedish - svenska" },
  { code: "tg", name: "Afrikaans", name2: "Tajik - тоҷикӣ" },
  { code: "ta", name: "Afrikaans", name2: "Tamil - தமிழ்" },
  { code: "tt", name: "Afrikaans", name2: "Tatar" },
  { code: "te", name: "Afrikaans", name2: "Telugu - తెలుగు" },
  { code: "th", name: "Afrikaans", name2: "Thai - ไทย" },
  { code: "ti", name: "Afrikaans", name2: "Tigrinya - ትግርኛ" },
  { code: "to", name: "Afrikaans", name2: "Tongan - lea fakatonga" },
  { code: "tr", name: "Afrikaans", name2: "Turkish - Türkçe" },
  { code: "tk", name: "Afrikaans", name2: "Turkmen" },
  { code: "uk", name: "Afrikaans", name2: "Twi" },
  { code: "tw", name: "Afrikaans", name2: "Ukrainian - українська" },
  { code: "ur", name: "Afrikaans", name2: "Urdu - اردو" },
  { code: "ug", name: "Afrikaans", name2: "Uyghur" },
  { code: "uz", name: "Afrikaans", name2: "Uzbek - o‘zbek" },
  { code: "vi", name: "Afrikaans", name2: "Vietnamese - Tiếng Việt" },
  { code: "wa", name: "Afrikaans", name2: "Walloon - wa" },
  { code: "cy", name: "Afrikaans", name2: "Welsh - Cymraeg" },
  { code: "fy", name: "Afrikaans", name2: "Western Frisian" },
  { code: "xh", name: "Afrikaans", name2: "Xhosa" },
]

export const languageLevels = [
  'Native', 'Fluent', 'Intemedia', 'Basic'
]